### ISSUE TITLE
Transfer to Tailscale's github org?

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale-chocolatey#12]
@zombiezen, mind if we transfer this repo to Tailscale's github org?

**Comment by zombiezen** [comment]
SGTM! LMK if you need additional access to do so.

**Comment by bradfitz** [comment]
Looks like I do. I don't see the option so maybe I need to be an owner or whatnot?

**Comment by zombiezen** [comment]
Ah okay, I think I can't directly add it to Tailscale, but I can transfer it to you.

**Comment by bradfitz** [comment]
Sorry, just got to this after the weekend and:

> Oops! That repository transfer has expired.

**Comment by zombiezen** [comment]
Initiated a new transfer. Does this one work?

**Comment by bradfitz** [comment]
Done:
https://github.com/tailscale/tailscale-chocolatey

And https://github.com/zombiezen/tailscale-chocolatey redirects. Yay, thanks!
