### ISSUE TITLE
Update to latest version

### ISSUE THREAD

**Issue by ckuehl** [tailscale/tailscale-chocolatey#28]
Given https://tailscale.com/blog/windows-updates/, can we get this package updated to the latest version?

**Comment by ckuehl** [comment]
Related: even though #27 was committed, it doesn't look like Chocolatey has anything after 1.14.0: https://community.chocolatey.org/packages/tailscale

**Comment by bradfitz** [comment]
Done. In moderation. Should be out in an hour or two.
